### ISSUE TITLE
AuthHost gives ENOTFOUND on subdomains

### ISSUE THREAD

**Issue by Crowdedlight** [tlaverdure/laravel-echo-server#212]
When I try to use following configuration it gives me error in the console. Been trying all sort of stuff but can't get it to work. 

Config:
```json
{
	"authHost": "inv.localhost:8080",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "inventorymananger",
			"key": "99ae389c9dd0300c56c79a653fcb073b"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "crow.ovh"
		},
		"sqlite": {}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": ""
}
```

Console output:
```
[02:19:33] - Error authenticating xfn3U1i6yH1fREY3AAAA for private-update.sales.${eventID}
Error: getaddrinfo ENOTFOUND inv.localhost inv.localhost:8080
Error sending authentication request.
[02:21:18] - Error authenticating FN-kTE-eqfYjtGCUAAAD for private-update.sales.${eventID}
Error: getaddrinfo ENOTFOUND inv.localhost inv.localhost:8080
Error sending authentication request.
``` 

If I change my vhost and authHost so ``http://localhost:8080`` points at my application it seems to find it. (I get different error with authorization)

Sidenote: Is laravel setup to handle the ``/broadcasting/auth`` route by default when broadcastprovider is uncommented? Because the error I get when changing vhost & authHost to ``localhost:8080`` seems like it just get access denied (Route doesn't exists)

Let me know if you need more information or have any ideas how to solve this, as it's driving me insane atm.

**Comment by catalinux** [comment]
Your larave-echo-server will make request to `inv.localhost` domain. You have to make sure that `inv.localhost` is resolved o that machine.

Adding in /etc/hosts 

```
127.0.0.1 inv.localhost
```

will hel

**Comment by Crowdedlight** [comment]
ah yeah ofc. That did the trick. 

Getting following error now though:
```
{"error":"Unauthenticated."}
Client can not be authenticated, got HTTP status 401
``` 

But got no idea why it can't be authed, as I got it defined in channels.php
```php
Broadcast::channel('update.sales.{eventID}', function ($user, $eventID) {
    return true;
    //return (int) $user->FK_eventID === (int) $eventID;
});
```

Echo-client:
```php
const Echo = require("laravel-echo");
const io = window.io = require('socket.io-client');

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
});
```

```js
    window.Echo.private('update.sales.{{$user->event()->id}}')
            .listen('SalesUpdated', (e) => {
                console.log(e);
    });
```

And not sure exactly what that error tells me, besides something with auth is going wrong.

**Comment by catalinux** [comment]
When you call for `Echo.private('update.sales.{{$user->event()->id}}'` that means that your socket server would ask your app for if that request is legitimate.

in your  `routes/channels.php`  you need to setup your channels and respond with true if that request is auth.

Steps are like that

1. Your browser will tell your server its authorization
2. Your laravel-echo-server will ask for auth to your app
3. If OK, your server will authorizae your "private" call.

You should write in your browser console localStorage.debug='*' so you have detailed info about the comunication

**Comment by Crowdedlight** [comment]
I get that. I just don't get why it doesn't work when I do have ``routes/channels.php`` setup like this:
```php
Broadcast::channel('private-update.sales.{eventID}', function ($user, $eventID) {
    return true;
    //return (int) $user->FK_eventID === (int) $eventID;
});
```

To my understanding this should auth anyone that ask. I have checked output in browser console and laravel-echo-server cmd, and it is the same channel it tries to auth on. So I can confirm that the channel name matches the one in ``routes/channels.php``, but I still get ``401`` error. 

The browser console log says it sends this: 
```
["subscribe",{"channel":"private-update.sales.1","auth":{"headers":{"X-CSRF-TOKEN":"f3ys0CbJLhMro2KeAPNEogELqVvG3F7prJgGVtRm"}}}]
```
And the ``laravel-echo-server`` confirms it recieve the request and try and auth that channel. 

Is there a way to see a more verbose log of laravel-echo-server to try and debug what goes wrong when it asks laravel app for the auth? 
``logs/laravel.log`` is empty and doesn't provide any errors.

**Comment by catalinux** [comment]
You could add log debug info from channel authorization from you laravel app. It seems your server  is doing fine

**Comment by Crowdedlight** [comment]
So, Quite frankly I got no idea what I changed, but it works now. Think it must have been a mismatch between routes. As it appeared they didn't hit the actual routes.
