### ISSUE TITLE
The server don't listening for redis events... why ?

### ISSUE THREAD

**Issue by Xationch** [tlaverdure/laravel-echo-server#214]
Hi, 
When I strat the laravel-echo-server : 

```
✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
```

It's seem to missing the ```✔  Listening for redis events...```

And actually when I monitor ``` redis-cli monitor ``` I don't see the subscribe. What I'm doing wrong ?

```
{
	"authHost": "http://localhost:8000",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "xxx",
			"key": "xxx"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": ""
}
```

**Comment by catalinux** [comment]
1. What do you call from the browser?
2. Does your laravel  app responses to "http://localhost:8000",?

**Comment by Xationch** [comment]
1. Not sure to understand the question:

```
Echo = new Echo({
	broadcaster: 'socket.io',
	host: window.location.hostname + ':6001'
})

Echo.channel('chan-demo')
	.listen('TestEvent', (e) => {
		console.log(e)
	})
```

2. Yes

The subsribe with Echo work:
```
[15:49:47] - 2cy2LkdWfTl78fTdAAAB joined channel: chan-demo
```

The Redis Publish work:
```1504187319.694466 [0 127.0.0.1:60952] "SELECT" "0"
1504187319.701394 [0 127.0.0.1:60952] "PUBLISH" "chan-demo" "{\"event\":\"App\\\\Events\\\\TestEvent\",\"data\":{\"message\":\"Hello\",\"socket\":null},\"socket\":null}"```

But not the subscribe from the laravel-echo-server

**Comment by catalinux** [comment]
1. Ok. Want it to know if you subscribe to a public or private channel
2. You listen for TestEvent but you push the class name with the namespace also. There are some differences between laravel-echo (not server) 1.3.2 and 1.3.0  about how it formats events.

On your php Event your should define your events something like a string:

```php
    public function broadcastAs()
    {
        return 'alerts.created';
    }
```

And on 1.3.2 version you should listen for:

```js
channel.listen('.alerts.created', (event) => {

**Comment by approached** [comment]
I had many trouble with this same problem... just add a dod.

```
 TestEvent => .TestEvent

Echo.channel('chan-demo')
	.listen('.TestEvent', (e) => {
		console.log(e)
	})

or

window.Echo.listen('chan-demo', '.TestEvent', data => this.addPost(data));
```

**Comment by Xationch** [comment]
@catalinux I'm runing the laravel-echo 1.3.0 version. I do not know if it helps but with pusher it works very well. That's why I did not think the problem comes from Echo or my events.

I'm listening for both. One public and one private. Same issue : I see the joined channel on laravel-echo-server, but no subscription on the redis monitor.

I already try with the dot and the broadcastAs.

**Comment by catalinux** [comment]
Does it fail when redis is stopped ? Make sure you use same redis instance.

as @approached : take care of this buggy thing: https://github.com/laravel/echo/issues/147

**Comment by anouarabdsslm** [comment]
@Xationch since you are using homestead did you tried to set the broadcast driver to redis on local too. i think you have it set to log and this way data get not broadcasted to front-end just get logged to the log file.

**Comment by Xationch** [comment]
@anouarabdsslm on the broadcasting.php file ? Yes, it's redis. ```'default' => 'redis',```

```
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],
```

**Comment by jjhesk** [comment]
@Xationch 
what is the new solution now

**Comment by Xationch** [comment]
@jjhesk  I never found a solution after. I went back to Pusher because I'm alone on the project and no more time to lose.

**Comment by josteph** [comment]
@Xationch Have you set the QUEUE_DRIVER to redis in .env file? If so, run `php artisan queue:work` command and you should be able to listen to redis event. Same thing happened to me before.

**Comment by mikebronner** [comment]
I have been unable to get this to listen to redis as well. I am using
Homestead,
Laravel 5.5, 
laravel-echo: 1.3.4,
laravel-echo-server: 1.3.6,

Any suggestions for how to get this to listen to redis events? I have tried many suggestions from various issues in this repo, but nothing seems to work. Here is my configuration and output:

```
{
	"authHost": "http://localhost",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": false,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"apiOriginAllow": {
		"allowCors": false,
		"allowOrigin": "",
		"allowMethods": "",
		"allowHeaders": ""
	}
}
```

```
L A R A V E L  E C H O  S E R V E R

version 1.3.6

Starting server...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
```

**Comment by josteph** [comment]
@mikebronner Please follow the steps below

1. In laravel-echo-server.json, change your databaseConfig:
```
       "authHost": "http://localhost:8000",
       "databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "http://localhost:8000"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
```

2. In .env file, set BROADCAST_DRIVER and QUEUE_DRIVER to redis
3. Start redis server `./redis-server` in your redis `src` directory
4. Run `php artisan queue:work`
5. You should be able to listen for redis event now.

**Comment by decodedmrq** [comment]
I'm getting same issue. Echo server not listening redis event ? Any help. Thank you.

**Comment by decodedmrq** [comment]
Add databaseConfig redis to your laravel-echo-server.json file.

**Comment by mikebronner** [comment]
I finally got it working with this configuration:
```
{
	"authHost": "http://geneamatic.dev.genealabs.com",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {
            "port": "6379",
            "host": "geneamatic.dev.genealabs.com"
        }
	},
	"devMode": true,
	"host": "",
	"port": "6001",
	"protocol": "redis",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"apiOriginAllow": {
		"allowCors": false,
		"allowOrigin": "",
		"allowMethods": "",
		"allowHeaders": ""
	}
}
```

**Comment by josteph** [comment]
Yes, don't forget to setup the redis databaseConfig part!

**Comment by CatoMinor** [comment]
FWIW, I had pretty much the same problem as **Xationch**:
(1) `✔ Listening for redis events...` is the one comment missing when laravel-echo-server starts.
(2)  In `redis-subscriber.js`, typing `console.log('blah')` in various places suggests something is going wrong at ` _this._redis.psubscribe('*', function (err, count)` but no error message is produced.
(3) Laravel-echo-server _does_ show users joining/exiting channels via Echo.
(4) `redis-cli monitor` shows events are being `PUBLISH`-ed.
(5) I have played around with numerous little suggested changes to all the configuration files and no luck.
(6) Pusher works fine, even if it's not what I'd ideally use, so I'll probably use Pusher for now.

Laravel 5.5
Homestead 5.0.1
Laravel Echo 1.3.4
Laravel-echo-server 1.3.6
Windows 10

**Comment by josteph** [comment]
@CatoMinor Perhaps your config file is misconfigured.

**Comment by skeith69** [comment]
I have the same problem.
Running the command inside Homestead server.

DIR ~/code/chillwithluna
COMMAND laravel-echo-server start

L A R A V E L  E C H O  S E R V E R

version 1.3.6

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...
(node:8392) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Redis could not subscribe.
(node:8392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Windows 10 Home Single Language
Node 8.9.4
Laravel Echo 1.3.5
Socket.io-client 2.0.4
Using Homestead IP 192.168.69.69
domain https://chillwithluna.dev (Local connecting to homestead, I'm using self verified SSL cert & key)

laravel-echo-server.json

{
	"authHost": "https://chillwithluna",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "94c7b348052812b4",
			"key": "adf91495376124a0765ff0352594e269"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "192.168.69.69"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "redis",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"apiOriginAllow": {
		"allowCors": false,
		"allowOrigin": "",
		"allowMethods": "",
		"allowHeaders": ""
	}
}


bootstrap.js

import Echo from "laravel-echo";

window.io = require('socket.io-client');

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: '192.168.69.69:6001'
});

**Comment by diadal** [comment]
I have same problem I get it start 


L A R A V E L  E C H O  S E R V E R

version 1.3.6

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

by doing

`"databaseConfig": {
		"redis": {
			"port": "6379",
			"password": "xxxxxxxx",
			"host": "127.0.0.1"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},`

the xxxxxxxx is your redis password it works

**Comment by diadal** [comment]
`[18:26:05] - 2ZSuBxaT6F1Q4ecjAAAA joined channel: chat
[18:26:07] - XW9MQuBjhm6l6so2AAAB joined channel: chat` show your redis is working if you are not getting message via your channel that mean your broadcasting name and notification channel name are not thesame I have same issue before I fixed this correcting the names

**Comment by JellyBool** [comment]
> your broadcasting name and notification channel name ?

Here is my MessageCreated class:

```php
class MessageCreated implements ShouldBroadcast {
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('chat');
    }


    public function broadcastAs()
    {
        return 'message.created';
    }
}
```
My Vuejs component:
```
 created() {
             window.Echo.channel('chat')
                .listen('message.created', (e) => {
                    console.log(e)
                    this.messages.push(e.message.body)
                })
        },
```
@diadal

**Comment by diadal** [comment]
try this 

`
created() {
             window.Echo.channel('chat')
                .listen('.chat', (e) => {
                    console.log(e)
                    this.messages.push(e.message.body)
                })
        },

`
or just simple 

` 
Echo.channel('chat')
    .listen('.chat', (e) => {
                   console.log(e)
                    this.messages.push(e.message.body)
      });
`
just do any of this dont remove the `.` before `chat`

**Comment by JellyBool** [comment]
I tried
```js
 window.Echo.channel('chat')
                .listen('.chat', (e) => {
                    console.log(e)
                    this.messages.push(e.message.body)
                })
```
with MessageCreated class 
```php

class MessageCreated implements ShouldBroadcast {
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('chat');
    }
}
```

Still not working...
@diadal

**Comment by diadal** [comment]
paste your channel route 

but try this  with the 
`
window.Echo.channel('chat')
                .listen('.chat', (e) => {
                    console.log(e)
                    this.messages.push(e.message.body)
                })

`

`
class MessageCreated implements ShouldBroadcast {
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('chat');
    }

    public function broadcastWith()
    {
        return ['msg' => $this->message];
    }
}
`

**Comment by JellyBool** [comment]
channel routes
```php
<?php

Broadcast::channel('chat', function () {
    return true;
});
```
I'll try your solution. Thanks in advance.

**Comment by diadal** [comment]
the last solution I sent work with your route 

public function broadcastWith()
    {
        return ['msg' => $this->message];
    }
if you dont get your msg 

echo $this->message; it will show in your cmd console under laravel-echo-server there you can figure out what error or problem is goodluck

**Comment by JellyBool** [comment]
I tried echo $this->message,it shows up in my queue:work console:
```
php artisan queue:work
[2018-07-08 19:20:18][zenwY150EyPgDTYkV16cDdikiqY1mN7J] Processing: App\Events\MessageCreated
{"id":15,"body":"scdd","created_at":"2018-07-08 19:20:18","updated_at":"2018-07-08 19:20:18"}[2018-07-08 19:20:18][zenwY150EyPgDTYkV16cDdikiqY1mN7J] Processed:  App\Events\MessageCreated
```

Nothing on laravel-echo-server console
```
 laravel-echo-server start

L A R A V E L  E C H O  S E R V E R

version 1.3.6

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
[19:18:50] - GUt-aOcE-63sHS2lAAAA joined channel: chat
[19:18:52] - jHeDgb19wS5iKFsrAAAB joined channel: chat
[19:19:07] - GUt-aOcE-63sHS2lAAAA left channel: chat (transport close)
[19:19:07] - kdYbKUh96630Zm5RAAAC joined channel: chat
[19:19:13] - jHeDgb19wS5iKFsrAAAB left channel: chat (transport close)
[19:19:13] - BDnWA00xswW2DuSXAAAD joined channel: chat
[19:20:51] - kdYbKUh96630Zm5RAAAC left channel: chat (transport close)
[19:20:52] - oOqgij5sd3-_YvfsAAAE joined channel: chat
[19:20:53] - BDnWA00xswW2DuSXAAAD left channel: chat (transport close)
[19:20:54] - YXXYM2pqJAf2P7NAAAAF joined channel: chat
```

**Comment by diadal** [comment]
oh Yes  that is right  add this to your event 

 public function broadcastAs()
    {
        return 'chat';
    }

 restart your queue:work after changing in your event

**Comment by diadal** [comment]
how did you call your event if you use ->toOthers(); remove it for now

**Comment by JellyBool** [comment]
Event call
```
Route::post('/post', function () {

    $message = \App\Message::create([
        'body' => request('body'),
    ]);

    MessageCreated::dispatch($message);

    return request('body');

});
```

**Comment by JellyBool** [comment]
I try everything I could... still not working

**Comment by JellyBool** [comment]
`.env`
```
BROADCAST_DRIVER=redis
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=redis
```
`laravel-echo-server.json`
```json
{
	"authHost": "http://bsn.test",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "aa1f1a58b0a4ed24",
			"key": "4a8b8b62a7e0e08846b24404b12cc00c"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis" : {
			"port": "6379",
			"password":"password",
			"host": "bsn.test"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"apiOriginAllow": {
		"allowCors": false,
		"allowOrigin": "",
		"allowMethods": "",
		"allowHeaders": ""
	}
}
```
`MessageCreated` class
```php
class MessageCreated implements ShouldBroadcast {
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('chat');
    }

    public function broadcastAs()
    {
        return 'chat';
    }

    public function broadcastWith()
    {
        return ['msg' => $this->message];
    }
}
```
`booststrap.js`
```js
window.io = require('socket.io-client')

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001',
});
```
Vuejs component
```js
created() {
             window.Echo.channel('chat').listen('.chat', (e) => {
                    // tried .listen('chat', (e) => {})
                    console.log(e)
                    this.messages.push(e.message.body)
                })

        },
```

**Comment by diadal** [comment]
this my config 
```
{
	"authHost": "http://dev.test",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "ew3da66bda1aede8",
			"key": "4ddb8ac3af2ce81c92ddc11d364xfd"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6339",
			"password": "00bdfc77bb5726986bdac04dd99e311afa6e98",
			"host": "dev.test"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": false,
	"host": "localhost",
	"port": "6001",
	"protocol": "http",
	"socketio": {
    "wsEngine": "ws"
		},
	"sslCertPath": "/Users/Zpeter/.valet/Certificates/dev.test.crt",
	"sslKeyPath": "/Users/Zpeter/.valet/Certificates/dev.test.key",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"apiOriginAllow": {
		"allowCors": true,
		"allowOrigin": "http://dev.test",
		"allowMethods": "GET, POST",
		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	}
}

**Comment by JellyBool** [comment]
Thanks!! I am still trying to figure it out.

Thanks again. @diadal

**Comment by JellyBool** [comment]
@tlaverdure Got any ideas?

**Comment by zedentox** [comment]
@JellyBool when you launch laravel-echo-server, are you in the Homestead shell ?

By default, you cant connect to redis from outside Homestead because the port is not open, check here for how to open it : https://laravel.com/docs/5.6/homestead#ports

You can also forward port 6001, depending from where you are launching LES...

Also, try to connect to Redis with the default client before trying to connect with LES.

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.

**Comment by jeffz2012** [comment]
It is still here.
I am using (trying to use) echo server 1.5.0 on Laravel 5.6, on development box on Xampp / Win10.
Events reach Redis (according to redis-cli monitor), echo server listens on 6001 (according to netstat) .
Nothing happens on console: 
L A R A V E L  E C H O  S E R V E R

version 1.5.0

Starting server...

✔  Running at la5 on port 6001
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

Also JS listener does not fire: 
`window.Echo.private('user.' + window.Laravel.user)
    .listen('PrivateEvent', (e) => {
        console.log(e);
    });`

It seems like using Ioredis is more reliable, but more pain to code inside of Laravel.

**Comment by dalexhd** [comment]
OMGGGG.
In my case I fixed by just adding a "implements ShouldBroadcast" on the event class.

```php
<?php

namespace App\Events\External;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class TestEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;
}
```

**Comment by darmen** [comment]
For anyone coming here, this worked for me. Just set `protocol` to `redis` in `laravel-echo-server.json` file.

**Comment by metallurgical** [comment]
For me it keeps failing when connecting redis server behind **TLS (Digital Ocean managed database)**. Below setting makes my life easier:

```
"redis": {
       "host": "hostname",
       "port": "25061", // Default port provided by DO
       "password": "password",
       "tls": {} // The most important setting
},
```

Hope helps someone out there that connecting with redis by Digital Ocean
